name: Build & Test Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0"

      - name: Restore workloads
        run: dotnet workload restore ./StarterApp/StarterApp.csproj

      - name: Restore dependencies
        run: dotnet restore ./StarterApp.sln

      - name: Build solution
        run: dotnet build ./StarterApp.sln -c Release --no-restore

      - name: Run tests
        run: dotnet test ./RentalApp.Test/RentalApp.Test.csproj -c Release --no-build --no-restore
