name: Build & Test Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Restore workloads
        run: dotnet workload restore ${{ vars.CSPROJ_PATH }}
      - name: Restore Dependencies
        run: dotnet restore ${{ vars.CSPROJ_PATH }}
      - name: Build Project
        run: dotnet build ${{ vars.CSPROJ_PATH }} -c Release --no-restore
      - name: Run Tests
        run: dotnet test ./RentalApp.Test/RentalApp.Test.csproj -c Release --no-build


