name: Documentation

on:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install doxygen -y

      - name: Generate Doxyfile
        run: doxygen -g Doxyfile

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: html

  deploy:
    needs: generate
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Output Page URL
        run: echo "GitHub Pages URL: ${{ steps.deployment.outputs.page_url }}"
